export const recentList = [
  {
    id: 1,
    img: 'https://office.hiworks.com/r2ware.com/common/logo',
    title: 'R2WARE',
    rec: 3,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '3시간전',
    commentTotal: 41,
    level: 77,
  },
  {
    id: 1,
    img: '/img',
    title: 'R2WARE',
    rec: 322,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '4시간전',
    commentTotal: 42,
    level: 77,
  },
  {
    id: 1,
    img: '/img',
    title: 'R2WARE',
    rec: 12,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '5시간전',
    commentTotal: 43,
    level: 77,
  },
  {
    id: 1,
    img: '/img',
    title: 'R2WARE',
    rec: 3,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '3시간전',
    commentTotal: 41,
    level: 77,
  },
  {
    id: 1,
    img: '/img',
    title: 'R2WARE',
    rec: 322,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '4시간전',
    commentTotal: 42,
    level: 77,
  },
  {
    id: 1,
    img: '/img',
    title: 'R2WARE',
    rec: 12,
    writer: '방주현연구원',
    toc: '기술연구소',
    inputDate: '5시간전',
    commentTotal: 43,
    level: 77,
  },
];

export const channelList = [
  { id: 0, channel: '기술연구소', postCnt: 4 },
  { id: 1, channel: '기술지원팀', postCnt: 5 },
  { id: 2, channel: '영업관리팀', postCnt: 6 },
  { id: 3, channel: '유지보수팀', postCnt: 7 },
  { id: 4, channel: '알투웨어', postCnt: 8 },
  { id: 5, channel: '부설연구소', postCnt: 9 },
  { id: 6, channel: '한산기', postCnt: 14 },
  { id: 7, channel: '에어컨', postCnt: 24 },
  { id: 8, channel: '서울숲IT', postCnt: 34 },
  { id: 9, channel: '캐슬', postCnt: 4 },
  { id: 10, channel: '동네들', postCnt: 45 },
  { id: 11, channel: '기술연구소', postCnt: 12 },
  { id: 12, channel: '기술지원팀', postCnt: 6 },
  { id: 13, channel: '영업관리팀', postCnt: 9 },
  { id: 14, channel: '유지보수팀', postCnt: 8 },
  { id: 15, channel: '알투웨어', postCnt: 3 },
  { id: 16, channel: '부설연구소', postCnt: 18 },
  { id: 17, channel: '한산기', postCnt: 22 },
  { id: 18, channel: '에어컨', postCnt: 19 },
  { id: 19, channel: '서울숲IT', postCnt: 33 },
  { id: 20, channel: '캐슬', postCnt: 21 },
  { id: 21, channel: '동네들', postCnt: 15 },
];
